--
-- File generated with SQLiteStudio v3.3.3 on Sun Oct 23 14:29:29 2022
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: playerDash_training_session
DROP TABLE IF EXISTS playerDash_training_session;
CREATE TABLE "playerDash_training_session" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "training_session_name" varchar(500) NOT NULL, "training_date" date NOT NULL, "coach_id" varchar(100) NOT NULL, "group_id" varchar(100) NOT NULL, "player_position" varchar(500) NOT NULL, "distance_travelled" real NOT NULL, "high_speed_distance_travelled" real NOT NULL, "player_veloity" real NOT NULL, "player_workload" integer NOT NULL, "sprint_distance_travelled" real NOT NULL, "player_id" varchar(100) NOT NULL);
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (1, 'Session S101', '10/10/2022', 'C002', 'G1', 'P001', 'Middle', 1000.0, 500.0, 50, 9.0, '200');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (2, 'Session S103', '13/10/2022', 'C003', 'G3', 'P003', 'Front', 800.0, 700.0, 100, 4.0, '400');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (3, 'Session S104', '13/10/2022', 'C003', 'G1', 'P001', 'Middle', 800.0, 600.0, 200, 7.0, '300');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (4, 'Session S105', '14/10/2022', 'C003', 'G1', 'P001', 'Middle', 800.0, 600.0, 300, 8.0, '400');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (5, 'Session S106', '13/10/2022', 'C003', 'G1', 'P001', 'Middle', 800.0, 400.0, 200, 9.0, '600');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (6, 'Session S107', '18/10/2022', 'C003', 'G1', 'P001', 'Middle', 700.0, 660.0, 500, 10.0, '400');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (7, 'Session S108', '19/10/2022', 'C001', 'G1', 'P001', 'Middle', 600.0, 800.0, 100, 11.0, '450');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (8, 'Session S109', '22/10/2022', 'C001', 'G1', 'P001', 'Middle', 1100.0, 600.0, 300, 8.0, '380');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (9, 'Session S110', '27/10/2022', 'C003', 'G1', 'P001', 'Middle', 1000.0, 500.0, 400, 9.0, '400');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (10, 'Session S101', '10/10/2022', 'C002', 'G1', 'P002', 'Back', 1000.0, 500.0, 50, 9.0, '200');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (11, 'Session S103', '13/10/2022', 'C003', 'G3', 'P002', 'Back', 800.0, 700.0, 100, 4.0, '400');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (12, 'Session S104', '13/10/2022', 'C003', 'G1', 'P002', 'Back', 800.0, 600.0, 200, 7.0, '300');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (13, 'Session S105', '14/10/2022', 'C003', 'G1', 'P002', 'Back', 800.0, 600.0, 300, 8.0, '400');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (14, 'Session S111', '18/10/2022', 'C003', 'G1', 'P001', 'Middle', 900.0, 700.0, 500, 7.0, '400');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (15, 'Session S112', '30/10/2022', 'C003', 'G1', 'P001', 'Middle', 800.0, 650.0, 600, 8.0, '450');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (16, 'Session S103', '13/10/2022', 'C003', 'G3', 'P004', 'Front', 400.0, 400.0, 500, 5.0, '300');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (17, 'Session S106', '13/10/2022', 'C003', 'G1', 'P002', 'Back', 800.0, 400.0, 200, 9.0, '600');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (18, 'Session S102', '11/10/2022', 'C001', 'G2', 'P002', 'Back', 1200.0, 400.0, 60, 8.0, '300');
INSERT INTO playerDash_training_session (id, training_session_name, training_date, coach_id, group_id, player_position, distance_travelled, high_speed_distance_travelled, player_veloity, player_workload, sprint_distance_travelled, player_id) VALUES (19, 'Session S102', '11/10/2022', 'C001', 'G2', 'P002', 'Back', 1200.0, 400.0, 60, 8.0, '300');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
