# Generated by Django 4.0.6 on 2022-07-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='playerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_no', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=40)),
                ('player_deviceId', models.CharField(max_length=40)),
                ('session_name', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('distance', models.FloatField()),
                ('high_speed_distance', models.FloatField()),
                ('sprint_distance', models.FloatField()),
                ('velocity', models.FloatField()),
                ('Workload', models.FloatField()),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
