# Generated by Django 4.0.6 on 2022-08-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Reg_User',
        ),
    ]
