# Generated by Django 4.0.6 on 2022-08-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_reg_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unreg_Users',
            fields=[
                ('email', models.EmailField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Reg_User',
        ),
        migrations.AddField(
            model_name='reg_users',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.unreg_users'),
        ),
    ]
