# Generated by Django 4.0.6 on 2022-10-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reg_users_unreg_users_delete_reg_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=25)),
                ('group_id', models.CharField(max_length=100)),
            ],
        ),
    ]
