# Generated by Django 4.0.6 on 2022-10-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('metric_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('group_performance', models.CharField(max_length=500)),
                ('player_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Training_Session',
            fields=[
                ('training_session_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('training_date', models.DateField(max_length=50)),
                ('coach_id', models.CharField(max_length=100)),
                ('group_id', models.CharField(max_length=100)),
                ('player_id', models.CharField(max_length=100)),
                ('player_position', models.CharField(max_length=500)),
            ],
        ),
    ]
