# Generated by Django 4.0.6 on 2022-10-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_metric_training_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('coach_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=25)),
                ('group_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200)),
                ('coach_id', models.CharField(max_length=100)),
                ('player_id', models.CharField(max_length=100)),
            ],
        ),
    ]
