# Generated by Django 4.0.6 on 2022-10-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_coach_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='player_comparison',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training_session',
            name='distance_travelled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='training_session',
            name='high_speed_distance_travelled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='training_session',
            name='player_veloity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='training_session',
            name='player_workload',
            field=models.IntegerField(default=1.1, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training_session',
            name='sprint_distance_travelled',
            field=models.FloatField(default=0.0),
        ),
    ]
