# Generated by Django 4.0.6 on 2022-10-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_metric_player_comparison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_session',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training_session',
            name='training_session_name',
            field=models.CharField(max_length=500),
        ),
    ]
