# Generated by Django 4.0.6 on 2022-10-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_training_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_session',
            name='training_date',
            field=models.CharField(max_length=50),
        ),
    ]
